/**
 * Type Definitions for Crypto Analytics Dashboard
 * 
 * These types define the data structures used throughout the application,
 * ensuring type safety and documenting the data model for the thesis.
 */

// Market data for a single crypto asset (from CoinGecko /coins/markets)
export interface CoinMarketData {
  id: string;
  symbol: string;
  name: string;
  image: string;
  current_price: number;
  market_cap: number;
  market_cap_rank: number;
  total_volume: number;
  price_change_24h: number;
  price_change_percentage_24h: number;
  price_change_percentage_1h: number;
  price_change_percentage_7d: number;
  price_change_percentage_30d: number;
  circulating_supply: number;
  total_supply: number | null;
  max_supply: number | null;
  ath: number;
  ath_change_percentage: number;
  ath_date: string;
  sparkline_7d: number[];
  fully_diluted_valuation: number | null;
  last_updated: string;
}

// Time-series data point
export interface TimeSeriesPoint {
  timestamp: number;
  date: string;
  value: number;
}

// Statistical summary of a dataset
export interface DataStats {
  price: {
    min: number;
    max: number;
    mean: number;
    start: number;
    end: number;
    change: number;
    stdDev: number;
  };
  volume: {
    min: number;
    max: number;
    mean: number;
    total: number;
  };
  dataPoints: number;
  timeRange: {
    start: string;
    end: string;
    days: number;
  };
}

// Historical data response from edge function
export interface HistoricalDataResponse {
  coinId: string;
  days: number;
  prices: TimeSeriesPoint[];
  volumes: TimeSeriesPoint[];
  marketCaps: TimeSeriesPoint[];
  stats: DataStats;
  timestamp: string;
  source: string;
  methodology: string;
}

// Market data API response
export interface MarketDataResponse {
  data: CoinMarketData[];
  timestamp: string;
  source: string;
  methodology: string;
}

// Chart data point with optional indicators
export interface ChartDataPoint {
  date: string;
  timestamp: number;
  price: number;
  volume?: number;
  marketCap?: number;
  ma7?: number;
  ma30?: number;
  ma200?: number;
  trendLine?: number;
}

// Analysis insight generated by the system
export interface AnalysisInsight {
  id: string;
  type: 'trend' | 'volume' | 'volatility' | 'comparison' | 'prediction' | 'support_resistance';
  severity: 'bullish' | 'bearish' | 'neutral';
  title: string;
  description: string;
  metric?: string;
  value?: number;
  timestamp: string;
}

// Dashboard configuration (persisted to localStorage)
export interface DashboardConfig {
  selectedCoins: string[];
  timeRange: number;
  showMA7: boolean;
  showMA30: boolean;
  showMA200: boolean;
  showTrendLine: boolean;
  primaryCoin: string;
  comparisonCoin: string;
  autoRefresh: boolean;
  refreshInterval: number; // seconds
}

// Supported coins
export const SUPPORTED_COINS = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin', color: '#F7931A' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum', color: '#627EEA' },
  { id: 'solana', symbol: 'SOL', name: 'Solana', color: '#9945FF' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano', color: '#0033AD' },
  { id: 'ripple', symbol: 'XRP', name: 'Ripple', color: '#23292F' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot', color: '#E6007A' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink', color: '#2A5ADA' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche', color: '#E84142' },
] as const;

export const TIME_RANGES = [
  { value: 7, label: '7D' },
  { value: 30, label: '30D' },
  { value: 90, label: '90D' },
  { value: 365, label: '1Y' },
] as const;

export const DEFAULT_CONFIG: DashboardConfig = {
  selectedCoins: ['bitcoin', 'ethereum', 'solana', 'cardano', 'ripple'],
  timeRange: 30,
  showMA7: true,
  showMA30: true,
  showMA200: false,
  showTrendLine: false,
  primaryCoin: 'bitcoin',
  comparisonCoin: 'ethereum',
  autoRefresh: true,
  refreshInterval: 120,
};


/**
 * Saved Analysis Report (persisted to Supabase database)
 * Demonstrates data persistence methodology for the thesis.
 */
export interface AnalysisReport {
  id: string;
  coin_id: string;
  coin_name: string;
  time_range: number;
  title: string;
  notes: string;
  insights: AnalysisInsight[];
  chart_config: {
    showMA7: boolean;
    showMA30: boolean;
    showMA200: boolean;
    showTrendLine: boolean;
    comparisonCoin: string;
  };
  stats_snapshot: DataStats | null;
  created_at: string;
}

/** Lightweight report listing (without full insights payload) */
export interface AnalysisReportSummary {
  id: string;
  coin_id: string;
  coin_name: string;
  time_range: number;
  title: string;
  notes: string;
  chart_config: AnalysisReport['chart_config'];
  created_at: string;
}
